server:
  port: ${AUTOFINANCE_SERVER_PORT:8585}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${AUTOFINANCE_DB_HOST:localhost}:${AUTOFINANCE_DB_PORT:5252}/${AUTOFINANCE_DB_NAME:autofinance_db_dev}?sslmode=${AUTOFINANCE_DB_SSLMODE:disable}
    username: ${AUTOFINANCE_DB_USERNAME:admin}
    password: ${AUTOFINANCE_DB_PASSWORD:password}

logging:
  level:
    org.hibernate.SQL: info
